console.log("hey this is umesh kumar");
let a=3;
let b=34;
console.log("sum =>",a+b);
let a1=23;
let b1=2.2;
let c="umesh";
let d=null;
let e=undefined;
console.log(a1,b1,c,d,e);
console.log(typeof a1,typeof b1,typeof c,typeof d,typeof e);
